datasets:
  &imagenet_train ilsvrc2012/train: !import_call
    _name: &dataset_name 'ilsvrc2012'
    _root: &root_dir !join ['~/datasets/', *dataset_name]
    key: 'torchvision.datasets.ImageFolder'
    init:
      kwargs:
        root: !join [*root_dir, '/train']
        transform: !import_call
          key: 'torchvision.transforms.Compose'
          init:
            kwargs:
              transforms:
                - !import_call
                  key: 'torchvision.transforms.RandomResizedCrop'
                  init:
                    kwargs:
                      size: &input_size [224, 224]
                - !import_call
                  key: 'torchvision.transforms.RandomHorizontalFlip'
                  init:
                    kwargs:
                      p: 0.5
                - !import_call
                  key: 'torchvision.transforms.ToTensor'
                  init:
                - !import_call
                  key: 'torchvision.transforms.Normalize'
                  init:
                    kwargs: &normalize_kwargs
                      mean: [0.485, 0.456, 0.406]
                      std: [0.229, 0.224, 0.225]
  &imagenet_val ilsvrc2012/val: !import_call
    key: 'torchvision.datasets.ImageFolder'
    init:
      kwargs:
        root: !join [*root_dir, '/val']
        transform: !import_call
          key: 'torchvision.transforms.Compose'
          init:
            kwargs:
              transforms:
                - !import_call
                  key: 'torchvision.transforms.Resize'
                  init:
                    kwargs:
                      size: 256
                - !import_call
                  key: 'torchvision.transforms.CenterCrop'
                  init:
                    kwargs:
                      size: *input_size
                - !import_call
                  key: 'torchvision.transforms.ToTensor'
                  init:
                - !import_call
                  key: 'torchvision.transforms.Normalize'
                  init:
                    kwargs: *normalize_kwargs

models:
  teacher_model:
    key: &teacher_model_name 'resnet50'
    _weights: &teacher_model_weights_enum !import_get
      key: 'torchvision.models.resnet.ResNet50_Weights'
    kwargs:
      num_classes: 1000
      weights: !getattr [*teacher_model_weights_enum, 'IMAGENET1K_V1']
  student_model:
    key: 'splittable_resnet'
    _weights: &student_model_weights_enum !import_get
      key: 'torchvision.models.resnet.ResNet50_Weights'
    kwargs:
      num_classes: 1000
      weights: !getattr [*student_model_weights_enum, 'IMAGENET1K_V1']
      bottleneck_config:
        key: 'larger_resnet_bottleneck'
        kwargs:
          bottleneck_channel: &bch 2
          bottleneck_idx: 12
          output_channel: 256
          compressor_transform: !import_call
            key: 'torchvision.transforms.Compose'
            init:
              kwargs:
                transforms:
                  - !import_call
                    key: 'sc2bench.transforms.misc.SimpleQuantizer'
                    init:
                      kwargs:
                        num_bits: 8
          decompressor_transform: !import_call
            key: 'torchvision.transforms.Compose'
            init:
              kwargs:
                transforms:
                  - !import_call
                    key: 'sc2bench.transforms.misc.SimpleDequantizer'
                    init:
                      kwargs:
                        num_bits: 8
      resnet_name: 'resnet50'
      pre_transform:
      skips_avgpool: False
      skips_fc: False
      analysis_config:
        analyzes_after_compress: True
        analyzer_configs:
          - key: 'FileSizeAnalyzer'
            kwargs:
              unit: 'KB'
    experiment: &experiment !join [*dataset_name, '-resnet50-bq', *bch, 'ch_from_', *teacher_model_name]
    dst_ckpt: !join ['./resource/ckpt/ilsvrc2012/supervised_compression/ghnd-bq/', *experiment, '.pt']

train:
  log_freq: 1000
  epoch_to_update: &epoch_to_update 20
  num_epochs: *epoch_to_update
  train_data_loader:
    dataset_id: *imagenet_train
    sampler:
      class_or_func: !import_get
        key: 'torch.utils.data.RandomSampler'
      kwargs:
    kwargs:
      batch_size: 64
      num_workers: 16
    cache_output:
  val_data_loader:
    dataset_id: *imagenet_val
    sampler:
      class_or_func: !import_get
        key: 'torch.utils.data.SequentialSampler'
      kwargs:
    kwargs:
      batch_size: 32
      num_workers: 16
      pin_memory: True
      drop_last: False
  teacher:
    sequential: ['conv1', 'bn1', 'relu', 'maxpool', 'layer1', 'layer2', 'layer3', 'layer4']
    frozen_modules: []
    forward_proc: 'forward_batch_only'
    forward_hook:
      input: []
      output: ['layer1', 'layer2', 'layer3', 'layer4']
    wrapper: 'DistributedDataParallel'
    requires_grad: False
  student:
    frozen_modules: ['layer2', 'layer3', 'layer4']
    forward_proc: 'forward_batch_only'
    forward_hook:
      input: []
      output: ['bottleneck_layer', 'layer2', 'layer3', 'layer4']
    wrapper: 'DistributedDataParallel'
    requires_grad: True
  optimizer:
    key: 'Adam'
    kwargs:
      lr: 0.001
  scheduler:
    key: 'MultiStepLR'
    kwargs:
      milestones: [5, 10, 15]
      gamma: 0.1
  criterion:
    key: 'WeightedSumLoss'
    kwargs:
      sub_terms:
        layer1:
          criterion:
            key: 'MSELoss'
            kwargs:
              reduction: 'sum'
          criterion_wrapper:
            key: 'SimpleLossWrapper'
            kwargs:
              input:
                is_from_teacher: False
                module_path: 'bottleneck_layer'
                io: 'output'
              target:
                is_from_teacher: True
                module_path: 'layer1'
                io: 'output'
          weight: 1.0
        layer2:
          criterion:
            key: 'MSELoss'
            kwargs:
              reduction: 'sum'
          criterion_wrapper:
            key: 'SimpleLossWrapper'
            kwargs:
              input:
                is_from_teacher: False
                module_path: 'layer2'
                io: 'output'
              target:
                is_from_teacher: True
                module_path: 'layer2'
                io: 'output'
          weight: 1.0
        layer3:
          criterion:
            key: 'MSELoss'
            kwargs:
              reduction: 'sum'
          criterion_wrapper:
            key: 'SimpleLossWrapper'
            kwargs:
              input:
                is_from_teacher: False
                module_path: 'layer3'
                io: 'output'
              target:
                is_from_teacher: True
                module_path: 'layer3'
                io: 'output'
          weight: 1.0
        layer4:
          criterion:
            key: 'MSELoss'
            kwargs:
              reduction: 'sum'
          criterion_wrapper:
            key: 'SimpleLossWrapper'
            kwargs:
              input:
                is_from_teacher: False
                module_path: 'layer4'
                io: 'output'
              target:
                is_from_teacher: True
                module_path: 'layer4'
                io: 'output'
          weight: 1.0

test:
  test_data_loader:
    dataset_id: *imagenet_val
    sampler:
      class_or_func: !import_get
        key: 'torch.utils.data.SequentialSampler'
      kwargs:
    kwargs:
      batch_size: 1
      num_workers: 16
      drop_last: False
