datasets:
  ilsvrc2012:
    name: &dataset_name 'ilsvrc2012'
    type: 'ImageFolder'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      train:
        dataset_id: &imagenet_train !join [*dataset_name, '/train']
        params:
          root: !join [*root_dir, '/train']
          transform_params:
            - type: 'WrappedRandomResizedCrop'
              params:
                size: &input_size [224, 224]
                interpolation: 'bicubic'
            - type: 'RandomHorizontalFlip'
              params:
                p: 0.5
            - &totensor
              type: 'ToTensor'
              params:
            - &normalize
              type: 'Normalize'
              params:
                mean: [0.5, 0.5, 0.5]
                std: [0.5, 0.5, 0.5]
      val:
        dataset_id: &imagenet_val !join [*dataset_name, '/val']
        params:
          root: !join [*root_dir, '/val']
          transform_params:
            - type: 'WrappedResize'
              params:
                size: 248
                interpolation: 'bicubic'
            - type: 'CenterCrop'
              params:
                size: *input_size
            - *totensor
            - *normalize

models:
  teacher_model:
    name: &teacher_model_name 'vit_small_r26_s32_224'
    params:
      num_classes: 1000
      pretrained: True
    experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
    ckpt: !join ['./resource/ckpt/ilsvrc2012/teacher/', *teacher_experiment, '.pt']
  student_model:
    name: &student_model_name 'splittable_hybrid_vit'
    params:
      num_classes: 1000
      pretrained: True
      num_pruned_stages: 1
      bottleneck_config:
        name: 'FPBasedResNetBottleneck'
        params:
          num_bottleneck_channels: &bch 64
          encoder_channel_sizes: [3, *bch, *bch, *bch]
          decoder_channel_sizes: [*bch, 512, 256, 256]
      hybrid_vit_name: *teacher_model_name
      pre_transform_params:
      skips_head: False
      analysis_config:
        analyzes_after_compress: True
        analyzer_configs:
          - type: 'FileSizeAnalyzer'
            params:
              unit: 'KB'
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_name, '_small_r26_s32_224-fp-beta20.48_from_hybrid_vit_small_r26_s32_224']
    ckpt: !join ['./resource/ckpt/ilsvrc2012/supervised_compression/entropic_student/', *student_experiment, '.pt']

train:
  log_freq: 1000
  epoch_to_update: &epoch_to_update 10
  stage1:
    num_epochs: *epoch_to_update
    train_data_loader:
      dataset_id: *imagenet_train
      random_sample: True
      batch_size: 64
      num_workers: 16
      cache_output:
    val_data_loader:
      dataset_id: *imagenet_val
      random_sample: False
      batch_size: 32
      num_workers: 16
    teacher:
      sequential: ['patch_embed.backbone.stem', 'patch_embed.backbone.stages']
      frozen_modules: []
      forward_hook:
        input: []
        output: ['patch_embed.backbone.stages.0', 'patch_embed.backbone.stages.1', 'patch_embed.backbone.stages.2', 'patch_embed.backbone.stages.3']
      wrapper: 'DistributedDataParallel'
      requires_grad: False
    student:
      adaptations:
      sequential: ['bottleneck_layer', 'patch_embed_pruned_stages']
      frozen_modules: ['patch_embed_pruned_stages']
      forward_hook:
        input: []
        output: ['bottleneck_layer', 'patch_embed_pruned_stages.1', 'patch_embed_pruned_stages.2', 'patch_embed_pruned_stages.3', 'bottleneck_layer.entropy_bottleneck']
      wrapper: 'DistributedDataParallel'
      requires_grad: True
    optimizer:
      type: 'Adam'
      params:
        lr: 0.001
    scheduler:
      type: 'MultiStepLR'
      params:
        milestones: [5, 8]
        gamma: 0.1
    criterion:
      type: 'GeneralizedCustomLoss'
      org_term:
        factor: 0.0
      sub_terms:
        stages0:
          criterion:
            type: 'MSELoss'
            params:
              reduction: 'sum'
          params:
            input:
              is_from_teacher: False
              module_path: 'bottleneck_layer'
              io: 'output'
            target:
              is_from_teacher: True
              module_path: 'patch_embed.backbone.stages.0'
              io: 'output'
          factor: 1.0
        stages1:
          criterion:
            type: 'MSELoss'
            params:
              reduction: 'sum'
          params:
            input:
              is_from_teacher: False
              module_path: 'patch_embed_pruned_stages.1'
              io: 'output'
            target:
              is_from_teacher: True
              module_path: 'patch_embed.backbone.stages.1'
              io: 'output'
          factor: 1.0
        stages2:
          criterion:
            type: 'MSELoss'
            params:
              reduction: 'sum'
          params:
            input:
              is_from_teacher: False
              module_path: 'patch_embed_pruned_stages.2'
              io: 'output'
            target:
              is_from_teacher: True
              module_path: 'patch_embed.backbone.stages.2'
              io: 'output'
          factor: 1.0
        stages3:
          criterion:
            type: 'MSELoss'
            params:
              reduction: 'sum'
          params:
            input:
              is_from_teacher: False
              module_path: 'patch_embed_pruned_stages.3'
              io: 'output'
            target:
              is_from_teacher: True
              module_path: 'patch_embed.backbone.stages.3'
              io: 'output'
          factor: 1.0
        bpp:
          criterion:
            type: 'BppLoss'
            params:
              entropy_module_path: 'bottleneck_layer.entropy_bottleneck'
              reduction: 'sum'
          factor: 20.48
  stage2:
    num_epochs: 20
    train_data_loader:
      dataset_id: *imagenet_train
      random_sample: True
      batch_size: 128
      num_workers: 16
      cache_output:
    val_data_loader:
      dataset_id: *imagenet_val
      random_sample: False
      batch_size: 32
      num_workers: 16
    teacher:
      sequential: []
      frozen_modules: []
      forward_hook:
        input: []
        output: []
      wrapper: 'DistributedDataParallel'
      requires_grad: False
    student:
      adaptations:
      sequential: []
      frozen_modules: ['bottleneck_layer.encoder', 'bottleneck_layer.entropy_bottleneck']
      forward_hook:
        input: []
        output: []
      wrapper: 'DistributedDataParallel'
      requires_grad: True
    optimizer:
      type: 'SGD'
      params:
        lr: 0.001
        momentum: 0.9
        weight_decay: 0.0005
    scheduler:
      type: 'MultiStepLR'
      params:
        milestones: [10]
        gamma: 0.1
    criterion:
      type: 'GeneralizedCustomLoss'
      org_term:
        criterion:
          type: 'KDLoss'
          params:
            temperature: 1.0
            alpha: 0.5
            reduction: 'batchmean'
        factor: 1.0
      sub_terms:

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 1
    num_workers: 16
