datasets:
  ilsvrc2012:
    name: &dataset_name 'ilsvrc2012'
    type: 'ImageFolder'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      val:
        dataset_id: &imagenet_val !join [*dataset_name, '/val']
        params:
          root: !join [*root_dir, '/val']
          transform_params:
            - type: 'Resize'
              params:
                size: 256
            - type: 'CenterCrop'
              params:
                size: &input_size [224, 224]
            - type: 'ToTensor'
              params:
            - type: 'AdaptivePad'
              params:
                fill: 0
                factor: 64

models:
  model:
    name: 'NeuralInputCompressionClassifier'
    params:
      post_transform_params:
        - type: 'CenterCrop'
          params:
            size: *input_size
        - type: 'Normalize'
          params:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
      analysis_config:
        analyzes_after_compress: True
        analyzer_configs:
          - type: 'FileSizeAnalyzer'
            params:
              unit: 'KB'
    compression_model:
      name: 'bmshj2018_factorized'
      params:
        pretrained: True
        quality: 8
        metric: 'mse'
      ckpt: './resource/ckpt/input_compression/factorized_prior.pt'
    classification_model:
      name: &model_name 'resnet50'
      params:
        num_classes: 1000
        pretrained: True
      experiment: &experiment !join [*dataset_name, '-', *model_name]
      ckpt: !join ['./resource/ckpt/', *experiment, '.pt']

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 1
    num_workers: 16
