datasets:
  &imagenet_train ilsvrc2012/train: !import_call
    _name: &dataset_name 'ilsvrc2012'
    _root: &root_dir !join ['~/datasets/', *dataset_name]
    key: 'torchvision.datasets.ImageFolder'
    init:
      kwargs:
        root: !join [*root_dir, '/train']
        transform: !import_call
          key: 'torchvision.transforms.Compose'
          init:
            kwargs:
              transforms:
                - !import_call
                  key: 'torchvision.transforms.RandomResizedCrop'
                  init:
                    kwargs:
                      size: &input_size [224, 224]
                - !import_call
                  key: 'torchvision.transforms.RandomHorizontalFlip'
                  init:
                    kwargs:
                      p: 0.5
                - !import_call
                  key: 'torchvision.transforms.ToTensor'
                  init:
                - !import_call
                  key: 'torchvision.transforms.Normalize'
                  init:
                    kwargs: &normalize_kwargs
                      mean: [0.485, 0.456, 0.406]
                      std: [0.229, 0.224, 0.225]
  &imagenet_val ilsvrc2012/val: !import_call
    key: 'torchvision.datasets.ImageFolder'
    init:
      kwargs:
        root: !join [*root_dir, '/val']
        transform: !import_call
          key: 'torchvision.transforms.Compose'
          init:
            kwargs:
              transforms:
                - !import_call
                  key: 'torchvision.transforms.Resize'
                  init:
                    kwargs:
                      size: 256
                - !import_call
                  key: 'torchvision.transforms.CenterCrop'
                  init:
                    kwargs:
                      size: *input_size
                - !import_call
                  key: 'torchvision.transforms.ToTensor'
                  init:
                - !import_call
                  key: 'torchvision.transforms.Normalize'
                  init:
                    kwargs: *normalize_kwargs

models:
  model:
    name: 'EntropicClassifier'
    kwargs:
      encoder_config:
        sequential: ['conv1', 'bn1', 'relu', 'maxpool', 'layer1']
      compression_model_kwargs:
        entropy_bottleneck_channels: 256
      decoder_config:
        sequential: ['layer2', 'layer3', 'layer4', 'avgpool']
      classifier_config:
        sequential: ['fc']
      analysis_config:
        analyzes_after_compress: True
        analyzer_configs:
          - key: 'FileSizeAnalyzer'
            kwargs:
              unit: 'KB'
    classification_model:
      name: &model_name 'resnet50'
      kwargs:
        num_classes: 1000
        pretrained: True
      src_ckpt: !join ['./resource/ckpt/', *dataset_name, '-', *model_name, '.pt']
    experiment: &experiment !join [*dataset_name, '-', *model_name, '-eb_after_layer1-beta1.0e-4']
    dst_ckpt: !join ['./resource/ckpt/ilsvrc2012/fine-tuning/', *experiment, '.pt']

train:
  log_freq: 1000
  epoch_to_update: &epoch_to_update 10
  num_epochs: *epoch_to_update
  train_data_loader:
    dataset_id: *imagenet_train
    random_sample: True
    batch_size: 128
    num_workers: 16
    cache_output:
  val_data_loader:
    dataset_id: *imagenet_val
    sampler: &val_sampler
      class_or_func: !import_get
        key: 'torch.utils.data.SequentialSampler'
      kwargs:
    kwargs:
      batch_size: 32
      num_workers: 16
      pin_memory: True
      drop_last: False
  model:
    forward_hook:
      input: []
      output: ['entropy_bottleneck']
    wrapper: 'DistributedDataParallel'
    requires_grad: True
  optimizer:
    key: 'Adam'
    kwargs:
      lr: 0.001
    grad_accum_step: 2
  scheduler:
    key: 'MultiStepLR'
    kwargs:
      milestones: [5, 8]
      gamma: 0.1
  criterion:
    key: 'GeneralizedCustomLoss'
    org_term:
      criterion:
        key: 'CrossEntropyLoss'
        kwargs:
          reduction: 'mean'
      factor: 1.0
    sub_terms:
      bpp:
        criterion:
          key: 'BppLoss'
          kwargs:
            entropy_module_path: 'entropy_bottleneck'
            reduction: 'batchmean'
        factor: 1.0e-4

test:
  test_data_loader:
    dataset_id: *imagenet_val
    sampler: *val_sampler
    kwargs:
      batch_size: 1
      num_workers: 16
      drop_last: False
