datasets:
  &pascal_val 'pascal_voc2012/val': !import_call
    _name: 'pascal_voc2012'
    _root: &root_dir '~/datasets'
    key: 'torchvision.datasets.VOCSegmentation'
    init:
    kwargs:
      root: *root_dir
      image_set: 'val'
      year: '2012'
      download: True
      transforms: !import_call
        key: 'custom.transform.CustomCompose'
        init:
          kwargs:
            transforms:
              - !import_call
                key: 'custom.transform.CustomRandomResize'
                init:
                kwargs:
                  min_size: 513
                  max_size: 513
              - !import_call
                key: 'sc2bench.transforms.misc.CustomToTensor'
                init:
		          kwargs:
				    converts_sample: False
				    converts_target: True

models:
  model:
    name: 'CodecInputCompressionSegmentationModel'
    kwargs:
      codec_encoder_decoder: !import_call
        key: 'torchvision.transforms.Compose'
        init:
          kwargs:
            transforms:
              - !import_call
                key: 'sc2bench.transforms.codec.BPGModule'
                init:
                  kwargs:
                    encoder_path: '~/software/libbpg-0.9.8/bpgenc'
                    decoder_path: '~/software/libbpg-0.9.8/bpgdec'
                    quality: 50
                    returns_file_size: True
      analysis_config:
        analyzer_configs:
          - key: 'FileSizeAccumulator'
            kwargs:
              unit: 'KB'
      post_transform: !import_call
        key: 'torchvision.transforms.Compose'
        init:
          kwargs:
            transforms:
              - !import_call
                key: 'torchvision.transforms.ToTensor'
                init:
              - !import_call
                key: 'torchvision.transforms.Normalize'
                init:
                  kwargs:
                    mean: [0.485, 0.456, 0.406]
                    std: [0.229, 0.224, 0.225]
    segmentation_model:
      name: 'deeplabv3_resnet50'
      kwargs:
        pretrained: True
        pretrained_backbone: True
        num_classes: 21
        aux_loss: True
      ckpt: 'https://github.com/yoshitomo-matsubara/torchdistill/releases/download/v0.2.8/pascal_voc2012-deeplabv3_resnet50.pt'

test:
  test_data_loader:
    dataset_id: *pascal_val
    random_sample: False
    batch_size: 1
    num_workers: 16
    collate_fn: 'pascal_seg_eval_collate_fn'
