datasets:
  pascal_voc:
    name: &dataset_name 'pascal_voc2012'
    type: 'VOCSegmentation'
    root: &root_dir '~/dataset'
    splits:
      val:
        dataset_id: &pascal_val !join [*dataset_name, '/val']
        params:
          root: *root_dir
          image_set: 'val'
          year: '2012'
          download: False
          transforms_compose_cls: 'CustomCompose'
          transforms_params: &val_transform
            - type: 'CustomRandomResize'
              params:
                min_size: 513
                max_size: 513
            - type: 'CustomToTensor'
              params:
                converts_sample: False
                converts_target: True

models:
  model:
    name: 'CodecInputCompressionSegmentationModel'
    params:
      codec_encoder_decoder:
      	!import_call
          key: 'torchvision.transforms.Compose'
          init:
            kwargs:
              transforms:
                - !import_call
                  key: 'sc2bench.transforms.codec.PILImageModule'
                  init:
                    kwargs:
                      format: 'WEBP'
                      quality: 90
                      returns_file_size: True
      analysis_config:
        analyzer_configs:
          - type: 'FileSizeAccumulator'
            params:
              unit: 'KB'
      post_transform:
        !import_call
        key: 'torchvision.transforms.Compose'
        init:
          kwargs:
            transforms:
              - !import_call
                key: 'torchvision.transforms.ToTensor'
                init:
              - !import_call
                key: 'torchvision.transforms.Normalize'
                init:
                  kwargs:
                    mean: [0.485, 0.456, 0.406]
                    std: [0.229, 0.224, 0.225]
    segmentation_model:
      name: 'deeplabv3_resnet101'
      params:
        pretrained: True
        pretrained_backbone: True
        num_classes: 21
        aux_loss: True
      ckpt: 'https://github.com/yoshitomo-matsubara/torchdistill/releases/download/v0.2.8/pascal_voc2012-deeplabv3_resnet101.pt'

test:
  test_data_loader:
    dataset_id: *pascal_val
    random_sample: False
    batch_size: 1
    num_workers: 16
    collate_fn: 'pascal_seg_eval_collate_fn'
