datasets:
  coco2017:
    name: &dataset_name 'coco2017'
    type: 'cocodetect'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      val:
        dataset_id: &coco_val !join [*dataset_name, '/val']
        images: !join [*root_dir, '/val2017']
        annotations: !join [*root_dir, '/annotations/instances_val2017.json']
        annotated_only: False

models:
  model:
    name: 'InputCompressionDetectionModel'
    params:
      codec_encoder_decoder:
      	!import_call
          key: 'torchvision.transforms.Compose'
          init:
            kwargs:
              transforms:
                - !import_call
                  key: 'sc2bench.transforms.codec.BPGModule'
                  init:
                    kwargs:
                      encoder_path: '~/software/libbpg-0.9.8/bpgenc'
                      decoder_path: '~/software/libbpg-0.9.8/bpgdec'
                      quality: 50
                      returns_file_size: True
      analysis_config:
        analyzer_configs:
          - type: 'FileSizeAccumulator'
            params:
              unit: 'KB'
        analyzes_after_compress: True
      adaptive_pad_config:
      pre_transform:
      post_transform:
    detection_model:
      name: 'fasterrcnn_resnet50_fpn'
      params:
        pretrained: True
        progress: True
        pretrained_backbone: True
      ckpt: ''

test:
  test_data_loader:
    dataset_id: *coco_val
    random_sample: False
    batch_size: 1
    num_workers: 4
    collate_fn: 'coco_collate_fn'
