dependencies:
  - name: 'custom'

datasets:
  &coco_train_dataset_id coco2017/train: !import_call
    _name: &dataset_name 'coco2017'
    _root: &root_dir !join ['~/datasets/', *dataset_name]
    key: 'coco.dataset.coco_dataset'
    init:
      kwargs:
        img_dir_path: !join [*root_dir, '/train2017']
        ann_file_path: !join [*root_dir, '/annotations/instances_train2017.json']
        annotated_only: True
        random_horizontal_flip: 0.5
        is_segment: False
  &coco_val_dataset_id coco2017/val: !import_call
    key: 'coco.dataset.coco_dataset'
    init:
      kwargs:
        img_dir_path: !join [*root_dir, '/val2017']
        ann_file_path: !join [*root_dir, '/annotations/instances_val2017.json']
        annotated_only: False
        is_segment: False

models:
  model:
    key: 'InputCompressionDetectionModel'
    kwargs:
      analysis_config:
        analyzer_configs:
          - key: 'FileSizeAnalyzer'
            kwargs:
              unit: 'KB'
        analyzes_after_compress: True
      adaptive_pad_kwargs:
        fill: 0
        padding_mode: 'constant'
        factor: 128
      pre_transform:
      post_transform:
      uses_cpu4compression_model: True
    compression_model:
      key: 'mbt2018'
      kwargs:
        pretrained: True
        quality: 8
        metric: 'mse'
      ckpt: './resource/ckpt/input_compression/joint_autoregressive_hierarchical_prior.pt'
    detection_model:
      key: 'fasterrcnn_resnet50_fpn'
      kwargs:
        pretrained: True
        progress: True
        pretrained_backbone: True
      ckpt: ''

test:
  test_data_loader:
    dataset_id: *coco_val_dataset_id
    random_sample: False
    batch_size: 1
    num_workers: 4
    collate_fn: 'coco_collate_fn'
