datasets:
  coco2017:
    name: &dataset_name 'coco2017'
    type: 'cocodetect'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      val:
        dataset_id: &coco_val !join [*dataset_name, '/val']
        images: !join [*root_dir, '/val2017']
        annotations: !join [*root_dir, '/annotations/instances_val2017.json']
        annotated_only: False

models:
  model:
    name: 'InputCompressionDetectionModel'
    params:
      codec_params:
        - type: 'BPGModule'
          params:
            encoder_path: '~/software/libbpg-0.9.8/bpgenc'
            decoder_path: '~/software/libbpg-0.9.8/bpgdec'
            quality: 50
            returns_file_size: True
      analysis_config:
        analyzer_configs:
          - type: 'FileSizeAnalyzer'
            params:
              unit: 'KB'
        analyzes_after_compress: True
      adaptive_pad_kwargs:
        fill: 0
        padding_mode: 'constant'
        factor: 128
      pre_transform_params:
      post_transform_params:
    compression_model:
      name: 'bmshj2018_factorized'
      params:
        pretrained: True
        quality: 8
        metric: 'mse'
      ckpt: './resource/ckpt/input_compression/factorized_prior.pt'
    detection_model:
      name: 'fasterrcnn_resnet50_fpn'
      params:
        pretrained: True
        progress: True
        pretrained_backbone: True
      ckpt: ''

test:
  test_data_loader:
    dataset_id: *coco_val
    random_sample: False
    batch_size: 1
    num_workers: 4
    collate_fn: 'coco_collate_fn'
