datasets:
  &imagenet_val ilsvrc2012/val: !import_call
    _name: &dataset_name 'ilsvrc2012'
    _root: &root_dir !join ['~/datasets/', *dataset_name]
    key: 'torchvision.datasets.ImageFolder'
    init:
      kwargs:
        root: !join [*root_dir, '/val']
        transform: !import_call
          key: 'torchvision.transforms.Compose'
          init:
            kwargs:
              transforms:
                - !import_call
                  key: 'torchvision.transforms.Resize'
                  init:
                    kwargs:
                      size: 256
                - !import_call
                  key: 'torchvision.transforms.CenterCrop'
                  init:
                    kwargs:
                      size: &input_size [224, 224]
                - !import_call
                  key: 'torchvision.transforms.ToTensor'
                  init:
                - !import_call
                  key: 'sc2bench.transforms.misc.AdaptivePad'
                  init:
                    kwargs:
                      fill: 0
                      factor: 64

models:
  model:
    key: 'NeuralInputCompressionClassifier'
    kwargs:
      post_transform:
        !import_call
        key: 'torchvision.transforms.Compose'
        init:
          kwargs:
            transforms:
              - !import_call
                key: 'torchvision.transforms.CenterCrop'
                init:
                  kwargs:
                    size: *input_size
              - !import_call
                key: 'torchvision.transforms.Normalize'
                init:
                  kwargs:
                    mean: [0.485, 0.456, 0.406]
                    std: [0.229, 0.224, 0.225]
      analysis_config:
        analyzes_after_compress: True
        analyzer_configs:
          - key: 'FileSizeAnalyzer'
            kwargs:
              unit: 'KB'
    compression_model:
      name: 'bmshj2018_factorized'
      kwargs:
        pretrained: True
        quality: 8
        metric: 'mse'
    classification_model:
      name: &model_name 'resnet50'
      kwargs:
        num_classes: 1000
        pretrained: True

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 1
    num_workers: 16
