datasets:
  &imagenet_val ilsvrc2012/val: !import_call
    _name: &dataset_name 'ilsvrc2012'
    _root: &root_dir !join ['~/datasets/', *dataset_name]
    key: 'torchvision.datasets.ImageFolder'
    init:
      kwargs:
        root: !join [*root_dir, '/val']
        transform: !import_call
          key: 'torchvision.transforms.Compose'
          init:
            kwargs:
              transforms:
                - !import_call
                  key: 'torchvision.transforms.Resize'
                  init:
                    kwargs:
                      size: 507
                      interpolation:
                        !getattr
                        - !import_get
                          key: 'torchvision.transforms.functional.InterpolationMode'
                        - 'BICUBIC'
                - !import_call
                  key: 'torchvision.transforms.CenterCrop'
                  init:
                    kwargs:
                      size: [475, 475]

models:
  model:
    key: 'CodecInputCompressionClassifier'
    kwargs:
      codec_encoder_decoder:
      	!import_call
          key: 'torchvision.transforms.Compose'
          init:
            kwargs:
              transforms:
                - !import_call
                  key: 'sc2bench.transforms.codec.PILImageModule'
                  init:
                    kwargs:
                      format: 'JPEG'
                      quality: 90
                      returns_file_size: True
      post_transform:
        !import_call
        key: 'torchvision.transforms.Compose'
        init:
          kwargs:
            transforms:
              - !import_call
                key: 'torchvision.transforms.ToTensor'
                init:
              - !import_call
                key: 'torchvision.transforms.Normalize'
                init:
                  kwargs:
                    mean: [0.485, 0.456, 0.406]
                    std: [0.229, 0.224, 0.225]
      analysis_config:
        analyzer_configs:
          - key: 'FileSizeAccumulator'
            kwargs:
              unit: 'KB'
    classification_model:
      name: &model_name 'tf_efficientnet_l2_ns_475'
      repo_or_dir: 'rwightman/pytorch-image-models'
      kwargs:
        num_classes: 1000
        pretrained: True

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 1
    num_workers: 16
